
http:
  port: "8081"

# The project artifact and version data 
project:
  artifact: "${project.artifactId}"
  version: "${project.version}"
  
# API Specification and autodiscovery
api:  
  group: "${restconnector.api.spec.group}"
  artifact: "${restconnector.api.spec.artifact}"
  version: "${restconnector.api.spec.version}"
  spec: "resource::${api.group}:${api.artifact}:${api.version}:raml:zip:api.raml"
  id: "17910674"

customer-api:
  host: "micorp-customer-sapi-dev.us-e2.cloudhub.io"
  port: "80"
  protocol: "HTTP"
  basepath: "/api"
  
order-api:
  host: "micorp-order-sapi-dev.us-e2.cloudhub.io"
  port: "80"
  protocol: "HTTP"
  basepath: "/api"

item-api:
  host: "micorp-item-sapi-dev.us-e2.cloudhub.io"
  port: "80"
  protocol: "HTTP"
  basepath: "/api"
  